//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointOpeOsaaminen.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Käyttäjät
    {
        public int KäyttäjäID { get; set; }
        [Required(ErrorMessage = "Käyttäjätunnus on pakollinen", AllowEmptyStrings = false)]
        [DisplayName("KäyttäjäTunnus")]
        public string KäyttäjäTunnus { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Salasana on pakollinen ", AllowEmptyStrings = false)]
        public string Salasana { get; set; }
        public string Loginerror { get; set; }
        public string InRole { get; set; }

    }
}
