//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointOpeOsaaminen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Käyttäjät
    {
        public int KäyttäjäID { get; set; }
        public string KäyttäjäTunnus { get; set; }
        public string Salasana { get; set; }
    }
}
