//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointOpeOsaaminen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpettajaOsaaminen
    {
        public int OpettajaOsaamisID { get; set; }
        public int OpettajaID { get; set; }
        public int OsaamisID { get; set; }
        public string OsaamisenKuvaus { get; set; }
    
        public virtual Opettaja Opettaja { get; set; }
        public virtual Osaaminen Osaaminen { get; set; }
    }
}
